### PR TITLE
Reorganized Assets/Create menu to group the tiles and brushes. 

### PR DESCRIPTION
**Pull request by janissimsons**
It was getting a bit messy having all the tiles and brushes directly under the Create menu, so I grouped them in separate submenus.

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
Please change all [MenuItem] to [CreateAssetMenu] by the way!
[MenuItem] is very inconvenient, it can't be created directly in the current directory.

**Comment by janissimsons** [comment]
Done, replaced MenuItem with CreateAssetMenu in the latest commit.

**Comment by johnsoncodehk** [comment]
Thank you!

**Comment by ChuanXin-Unity** [comment]
Thank you for organizing and updating this!

**Pull request merged**
