### PR TITLE
Prefab brush for Instantiating a selected prefab in editor. Moved the old functionality to PrefabRandomBrush.cs

### PR DESCRIPTION
**Pull request by vladderb**
This brush allows you to instantiate the selected prefab. You can delete both the selected one if ForceDetele is false and everything in the cell if you set ForceDetete to true.

### CODE REVIEW

**Comment by ChuanXin-Unity** [comment]
It seems that we could combine both of these brushes together into one by setting only one prefab into the brush (which disables the random selection) and checking for that single prefab when force delete is disabled.

What do you think about that?

**Comment by vladderb** [comment]
Hello! I do not quite agree with this. Rather, I will take out the general logic in a separate class, and PrefabBrush and PrefabRandomBrush will inherit it, so that in case of changing the main functionality (prefab spawn on the grid) we did not have to edit 2 classes at once. If we combine everything into one, we get a tool with a large number of fields, the meaning of which will not be fully understood. I proceed from the idea that the tool should be understandable, open and perform one single function, but perform it well.

Today I will look and resolve the conflicts that arose after your commit. Later I will make a base class and see how it will look.

**Comment by vladderb** [comment]
Carried out general functionality in the base class in order to avoid duplication of code and make future changes in logic simpler. Now PrefabBrush and PrefabRandomBrush only select the prefab that you want to spawn or delete, and use the base class logic to implement the removal or spawn.

**Comment by ChuanXin-Unity** [comment]
What you mention is fair, so let's go for that! Splitting up the base painting functionality is great and will keep things simple.

Thank you for working on this and sharing it!

**Pull request merged**
