### PR TITLE
RuleOverrideTile updates

### PR DESCRIPTION
**Pull request by johnsoncodehk**
### Changes
- [RuleOverrideTile] Move advanced mode to AdvancedRuleOverrideTile
- [RuleOverrideTile] Add GameObject overrides
- [RuleOverrideTile] List height lessen
- [RuleOverrideTile] Don't override null sprite
- [AdvancedRuleOverrideTile] Fix override rule lost reference when source rule reorder
- [AdvancedRuleOverrideTile] List GUI simplify
- [RuleOverrideTile / AdvancedRuleOverrideTile] Show unused overrides
- [RuleOverrideTile / AdvancedRuleOverrideTile] Support multiple inheritance
- [RuleOverrideTile / AdvancedRuleOverrideTile] Prevent circular reference
- [RuleTile] Fixed override tiles have not update when default properties changed
- [RuleTile] Hidden Rule field

### CODE REVIEW

**Comment by ChuanXin-Unity** [comment]
Hi, thanks for improving this further! Sorry, unfortunately, I may take a while reviewing this.

**Comment by ChuanXin-Unity** [comment]
With the addition of `AdvancedRuleOverrideTile`, in `RuleTile`, should the checks for `RuleOverrideTile` be changed to `RuleOverrideTileBase`?

**Comment by johnsoncodehk** [comment]
Yes!  Sorry I didn't test this out!  I can't use computer a few hours.  You can submit a patch or wait for my commit, thank you!

**Comment by johnsoncodehk** [comment]
@ChuanXin-Unity Because change checks to ```RuleOverrideTileBase``` will affect some people custom rule used case, so I remove ```RuleOverrideTileBase``` and changed ```AdvancedRuleOverrideTile``` base class to ```RuleOverrideTile```. Fortunately, this is not expensive.

**Comment by ChuanXin-Unity** [comment]
The changes look good, thanks!

**Pull request merged**
